const stateChoices = [
  {id: '00', displayName: '-'},
  {id: 'AL', displayName: 'Alabama'},
  {id: 'AK', displayName: 'Alaska'},
  {id: 'AZ', displayName: 'Arizona'},
  {id: 'AR', displayName: 'Arkansas'},
  {id: 'CA', displayName: 'California'},
  {id: 'CO', displayName: 'Colorado'},
  {id: 'CT', displayName: 'Connecticut'},
  {id: 'DE', displayName: 'Delaware'},
  {id: 'DC', displayName: 'District of Columbia'},
  {id: 'FL', displayName: 'Florida'},
  {id: 'GA', displayName: 'Georgia'},
  {id: 'HI', displayName: 'Hawaii'},
  {id: 'ID', displayName: 'Idaho'},
  {id: 'IL', displayName: 'Illinois'},
  {id: 'IN', displayName: 'Indiana'},
  {id: 'IA', displayName: 'Iowa'},
  {id: 'KS', displayName: 'Kansas'},
  {id: 'KY', displayName: 'Kentucky'},
  {id: 'LA', displayName: 'Louisiana'},
  {id: 'ME', displayName: 'Maine'},
  {id: 'MD', displayName: 'Maryland'},
  {id: 'MA', displayName: 'Massachusetts'},
  {id: 'MI', displayName: 'Michigan'},
  {id: 'MN', displayName: 'Minnesota'},
  {id: 'MS', displayName: 'Mississippi'},
  {id: 'MO', displayName: 'Missouri'},
  {id: 'MT', displayName: 'Montana'},
  {id: 'NE', displayName: 'Nebraska'},
  {id: 'NV', displayName: 'Nevada'},
  {id: 'NH', displayName: 'New Hampshire'},
  {id: 'NJ', displayName: 'New Jersey'},
  {id: 'NM', displayName: 'New Mexico'},
  {id: 'NY', displayName: 'New York'},
  {id: 'NC', displayName: 'North Carolina'},
  {id: 'ND', displayName: 'North Dakota'},
  {id: 'OH', displayName: 'Ohio'},
  {id: 'OK', displayName: 'Oklahoma'},
  {id: 'OR', displayName: 'Oregon'},
  {id: 'PA', displayName: 'Pennsylvania'},
  {id: 'RI', displayName: 'Rhode Island'},
  {id: 'SC', displayName: 'South Carolina'},
  {id: 'SD', displayName: 'South Dakota'},
  {id: 'TN', displayName: 'Tennessee'},
  {id: 'TX', displayName: 'Texas'},
  {id: 'UT', displayName: 'Utah'},
  {id: 'VT', displayName: 'Vermont'},
  {id: 'VA', displayName: 'Virginia'},
  {id: 'WA', displayName: 'Washington'},
  {id: 'WV', displayName: 'West Virginia'},
  {id: 'WI', displayName: 'Wisconsin'},
  {id: 'WY', displayName: 'Wyoming'}
];

const countryChoices = [
  {id: '00', displayName: '-'},
  {id: 'AF', displayName: 'Afghanistan'},
  {id: 'AL', displayName: 'Albania'},
  {id: 'DZ', displayName: 'Algeria'},
  {id: 'AS', displayName: 'America Samoa'},
  {id: 'AD', displayName: 'Andorra'},
  {id: 'AO', displayName: 'Angola'},
  {id: 'AI', displayName: 'Anguilla'},
  {id: 'AQ', displayName: 'Antarctica'},
  {id: 'AG', displayName: 'Antigua and Barbuda'},
  {id: 'AR', displayName: 'Argentina Republic'},
  {id: 'AM', displayName: 'Armenia'},
  {id: 'AW', displayName: 'Aruba'},
  {id: 'AU', displayName: 'Australia'},
  {id: 'AT', displayName: 'Austria'},
  {id: 'AZ', displayName: 'Azerbaijan'},
  {id: 'BS', displayName: 'Bahamas'},
  {id: 'BH', displayName: 'Bahrain'},
  {id: 'BD', displayName: 'Bangladesh'},
  {id: 'BB', displayName: 'Barbados'},
  {id: 'BY', displayName: 'Belarus'},
  {id: 'BE', displayName: 'Belgium'},
  {id: 'BZ', displayName: 'Belize'},
  {id: 'BJ', displayName: 'Benin'},
  {id: 'BM', displayName: 'Bermuda'},
  {id: 'BT', displayName: 'Bhutan'},
  {id: 'BO', displayName: 'Bolivia'},
  {id: 'BA', displayName: 'Bosnia and Herzegovina'},
  {id: 'BW', displayName: 'Botswana'},
  {id: 'BV', displayName: 'Bouvet Island'},
  {id: 'BR', displayName: 'Brazil'},
  {id: 'IO', displayName: 'British Indian Ocean Territory'},
  {id: 'BN', displayName: 'Brunei Darussalam'},
  {id: 'BG', displayName: 'Bulgaria'},
  {id: 'BF', displayName: 'Burkina Faso'},
  {id: 'BI', displayName: 'Burundi'},
  {id: 'KH', displayName: 'Cambodia'},
  {id: 'CM', displayName: 'Cameroon'},
  {id: 'CA', displayName: 'Canada'},
  {id: 'CV', displayName: 'Cape Verde'},
  {id: 'KY', displayName: 'Cayman Islands'},
  {id: 'CF', displayName: 'Central African Republic'},
  {id: 'TD', displayName: 'Chad'},
  {id: 'CL', displayName: 'Chile'},
  {id: 'CN', displayName: 'China'},
  {id: 'CX', displayName: 'Christmas Islands'},
  {id: 'CC', displayName: 'Cocos Islands'},
  {id: 'CO', displayName: 'Colombia'},
  {id: 'KM', displayName: 'Comoros'},
  {id: 'CG', displayName: 'Congo'},
  {id: 'CD', displayName: 'Democratic Republic of Congo'},
  {id: 'CK', displayName: 'Cook Islands'},
  {id: 'CR', displayName: 'Costa Rica'},
  {id: 'HR', displayName: 'Croatia'},
  {id: 'CU', displayName: 'Cuba'},
  {id: 'CW', displayName: 'CuraÃ§ao'},
  {id: 'CY', displayName: 'Cyprus'},
  {id: 'CZ', displayName: 'Czech Republic'},
  {id: 'CI', displayName: 'CÃ´te d\'Ivoire'},
  {id: 'DK', displayName: 'Denmark'},
  {id: 'DJ', displayName: 'Djibouti'},
  {id: 'DM', displayName: 'Dominica'},
  {id: 'DO', displayName: 'Dominican Republic'},
  {id: 'TP', displayName: 'East Timor'},
  {id: 'EC', displayName: 'Ecuador'},
  {id: 'EG', displayName: 'Egypt'},
  {id: 'SV', displayName: 'El Salvador'},
  {id: 'EE', displayName: 'Estonia'},
  {id: 'ET', displayName: 'Ethiopia'},
  {id: 'FK', displayName: 'Falkland Islands'},
  {id: 'FO', displayName: 'Faore Islands'},
  {id: 'FJ', displayName: 'Fiji'},
  {id: 'FI', displayName: 'Finland'},
  {id: 'FR', displayName: 'France'},
  {id: 'FX', displayName: 'France Metropolitan'},
  {id: 'GF', displayName: 'French Guiana'},
  {id: 'PF', displayName: 'French Polynesia'},
  {id: 'TF', displayName: 'French Southern Territories'},
  {id: 'GA', displayName: 'Gabon'},
  {id: 'GM', displayName: 'Gambia'},
  {id: 'GE', displayName: 'Georgia'},
  {id: 'DE', displayName: 'Germany'},
  {id: 'GH', displayName: 'Ghana'},
  {id: 'GI', displayName: 'Gibraltar'},
  {id: 'GR', displayName: 'Greece'},
  {id: 'GL', displayName: 'Greenland'},
  {id: 'GD', displayName: 'Grenada'},
  {id: 'GP', displayName: 'Guadeloupe'},
  {id: 'GU', displayName: 'Guam'},
  {id: 'GT', displayName: 'Guatemala'},
  {id: 'GN', displayName: 'Guinea'},
  {id: 'GW', displayName: 'Guinea-Bissau'},
  {id: 'GY', displayName: 'Guyana'},
  {id: 'HT', displayName: 'Haiti'},
  {id: 'HM', displayName: 'Heard & McDonald Island'},
  {id: 'HN', displayName: 'Honduras'},
  {id: 'HK', displayName: 'Hong Kong'},
  {id: 'HU', displayName: 'Hungary'},
  {id: 'IS', displayName: 'Iceland'},
  {id: 'IN', displayName: 'India'},
  {id: 'IR', displayName: 'Iran'},
  {id: 'IQ', displayName: 'Iraq'},
  {id: 'IE', displayName: 'Ireland'},
  {id: 'IM', displayName: 'Isle of Man'},
  {id: 'IL', displayName: 'Israel'},
  {id: 'IT', displayName: 'Italy'},
  {id: 'JM', displayName: 'Jamaica'},
  {id: 'JP', displayName: 'Japan'},
  {id: 'JO', displayName: 'Jordan'},
  {id: 'KZ', displayName: 'Kazakhstan'},
  {id: 'KE', displayName: 'Kenya'},
  {id: 'KI', displayName: 'Kiribati'},
  {id: 'KP', displayName: 'North Korea'},
  {id: 'KR', displayName: 'South Korea'},
  {id: 'KW', displayName: 'Kuwait'},
  {id: 'KG', displayName: 'Kyrgyzstan'},
  {id: 'LA', displayName: 'Laos'},
  {id: 'LV', displayName: 'Latvia'},
  {id: 'LB', displayName: 'Lebanon'},
  {id: 'LS', displayName: 'Lesotho'},
  {id: 'LR', displayName: 'Liberia'},
  {id: 'LY', displayName: 'Libya'},
  {id: 'LI', displayName: 'Liechtenstein'},
  {id: 'LT', displayName: 'Lithuania'},
  {id: 'LU', displayName: 'Luxembourg'},
  {id: 'MO', displayName: 'Macao'},
  {id: 'MK', displayName: 'Macedonia'},
  {id: 'MG', displayName: 'Madagascar'},
  {id: 'MW', displayName: 'Malawi'},
  {id: 'MY', displayName: 'Malaysia'},
  {id: 'MV', displayName: 'Maldives'},
  {id: 'ML', displayName: 'Mali'},
  {id: 'MT', displayName: 'Malta'},
  {id: 'MH', displayName: 'Marshal Islands'},
  {id: 'MQ', displayName: 'Martinique'},
  {id: 'MR', displayName: 'Mauritius'},
  {id: 'YT', displayName: 'Mayotte'},
  {id: 'MX', displayName: 'Mexico'},
  {id: 'FM', displayName: 'Micronesia'},
  {id: 'MD', displayName: 'Moldova'},
  {id: 'MC', displayName: 'Monaco'},
  {id: 'MN', displayName: 'Mongolia'},
  {id: 'ME', displayName: 'Montenegro'},
  {id: 'MS', displayName: 'Montserrat'},
  {id: 'MA', displayName: 'Morocco'},
  {id: 'MZ', displayName: 'Mozambique'},
  {id: 'MM', displayName: 'Myanmar'},
  {id: 'NA', displayName: 'Namibia'},
  {id: 'NR', displayName: 'Nauru'},
  {id: 'NP', displayName: 'Nepal'},
  {id: 'NL', displayName: 'Netherlands'},
  {id: 'NC', displayName: 'New Caledonia'},
  {id: 'NZ', displayName: 'New Zealand'},
  {id: 'NI', displayName: 'Nicaragua'},
  {id: 'NE', displayName: 'Niger'},
  {id: 'NG', displayName: 'Nigeria'},
  {id: 'NU', displayName: 'Niue'},
  {id: 'NF', displayName: 'Norfolk Island'},
  {id: 'MP', displayName: 'Northern Mariana Islands'},
  {id: 'NO', displayName: 'Norway'},
  {id: 'OM', displayName: 'Oman'},
  {id: 'PK', displayName: 'Pakistan'},
  {id: 'PW', displayName: 'Palau'},
  {id: 'PS', displayName: 'Palestine'},
  {id: 'PA', displayName: 'Panama'},
  {id: 'PG', displayName: 'Papa New Guinea'},
  {id: 'PY', displayName: 'Paraguay'},
  {id: 'PE', displayName: 'Peru'},
  {id: 'PH', displayName: 'Philippines'},
  {id: 'PN', displayName: 'Pitcairn'},
  {id: 'PL', displayName: 'Poland'},
  {id: 'PT', displayName: 'Portugal'},
  {id: 'QA', displayName: 'Qatar'},
  {id: 'RO', displayName: 'Romania'},
  {id: 'RU', displayName: 'Russia'},
  {id: 'RW', displayName: 'Rwanda'},
  {id: 'RE', displayName: 'Reunion'},
  {id: 'BL', displayName: 'Saint Barthelemy'},
  {id: 'SH', displayName: 'Saint Helena'},
  {id: 'KN', displayName: 'Saint Kitts and Nevis'},
  {id: 'LC', displayName: 'Saint Lucia'},
  {id: 'MF', displayName: 'Saint Martin'},
  {id: 'PM', displayName: 'Saint Pierre and Miquelon'},
  {id: 'VC', displayName: 'Saint Vincent and the Grenadines'},
  {id: 'WS', displayName: 'Samoa'},
  {id: 'SM', displayName: 'San Marino'},
  {id: 'ST', displayName: 'Sao Tome and Principe'},
  {id: 'SA', displayName: 'Saudi Arabia'},
  {id: 'SN', displayName: 'Senegal'},
  {id: 'RS', displayName: 'Serbia'},
  {id: 'SC', displayName: 'Seychelles'},
  {id: 'SL', displayName: 'Sierra Leone'},
  {id: 'SG', displayName: 'Singapore'},
  {id: 'SX', displayName: 'Sint Maarten'},
  {id: 'SK', displayName: 'Slovakia'},
  {id: 'SI', displayName: 'Slovenia'},
  {id: 'SB', displayName: 'Solomon Islands'},
  {id: 'SO', displayName: 'Somalia'},
  {id: 'ZA', displayName: 'South Africa'},
  {id: 'GS', displayName: 'South Georgia'},
  {id: 'SS', displayName: 'South Sudan'},
  {id: 'ES', displayName: 'Spain'},
  {id: 'LK', displayName: 'Sri Lanka'},
  {id: 'SD', displayName: 'Sudan'},
  {id: 'SR', displayName: 'Suriname'},
  {id: 'SJ', displayName: 'Svalbard and Jan Mayen'},
  {id: 'SZ', displayName: 'Swaziland'},
  {id: 'SE', displayName: 'Sweden'},
  {id: 'CH', displayName: 'Switzerland'},
  {id: 'SY', displayName: 'Syria'},
  {id: 'TW', displayName: 'Taiwan'},
  {id: 'TJ', displayName: 'Tajikistan'},
  {id: 'TZ', displayName: 'Tanzania'},
  {id: 'TH', displayName: 'Thailand'},
  {id: 'TL', displayName: 'Timor-Leste'},
  {id: 'TG', displayName: 'Togo'},
  {id: 'TK', displayName: 'Tokelau'},
  {id: 'TO', displayName: 'Tonga'},
  {id: 'TT', displayName: 'Trinidad and Tobago'},
  {id: 'TV', displayName: 'Tuvalu'},
  {id: 'UG', displayName: 'Uganda'},
  {id: 'UA', displayName: 'Ukraine'},
  {id: 'AE', displayName: 'United Arab Emirates'},
  {id: 'GB', displayName: 'United Kingdom'},
  {id: 'US', displayName: 'United States'},
  {id: 'UM', displayName: 'US Minor Outlying Islands'},
  {id: 'UY', displayName: 'Uruguay'},
  {id: 'UZ', displayName: 'Uzbekistan'},
  {id: 'VU', displayName: 'Vanuatu'},
  {id: 'VE', displayName: 'Venezuela'},
  {id: 'VN', displayName: 'Vietnam'},
  {id: 'VG', displayName: 'British Virgin Islands'},
  {id: 'VI', displayName: 'US Virgin Islands'},
  {id: 'WF', displayName: 'Wallis and Futuna'},
  {id: 'EH', displayName: 'Western Sahara'},
  {id: 'YE', displayName: 'Yemen'},
  {id: 'ZM', displayName: 'Zambia'},
  {id: 'ZW', displayName: 'Zimbabwe'},
  {id: 'AX', displayName: 'Aland Islands'}
];

const dmaChoices = [
  {id: '000', displayName: '-'},
  {id: '500', displayName: 'Portland/Auburn'},
  {id: '501', displayName: 'New York'},
  {id: '502', displayName: 'Binghamton'},
  {id: '503', displayName: 'Macon'},
  {id: '504', displayName: 'Philadelphia'},
  {id: '505', displayName: 'Detroit'},
  {id: '506', displayName: 'Boston'},
  {id: '507', displayName: 'Savannah'},
  {id: '508', displayName: 'Pittsburgh'},
  {id: '509', displayName: 'Fort Wayne'},
  {id: '510', displayName: 'Cleveland'},
  {id: '511', displayName: 'Washington DC'},
  {id: '512', displayName: 'Baltimore'},
  {id: '513', displayName: 'Flint/Saginaw/Bay City'},
  {id: '514', displayName: 'Buffalo'},
  {id: '515', displayName: 'Cincinnati'},
  {id: '516', displayName: 'Erie'},
  {id: '517', displayName: 'Charlotte'},
  {id: '518', displayName: 'Greensboro/High Point/Winston-Salem'},
  {id: '519', displayName: 'Charleston-Sc'},
  {id: '520', displayName: 'Augusta'},
  {id: '521', displayName: 'Providence/New Bedford'},
  {id: '522', displayName: 'Columbia-Ga'},
  {id: '523', displayName: 'Burlington/Plattsburgh'},
  {id: '524', displayName: 'Atlanta'},
  {id: '525', displayName: 'Albany-Ga'},
  {id: '526', displayName: 'Utica'},
  {id: '527', displayName: 'Indianapolis'},
  {id: '528', displayName: 'Miami/FOrt Lauderdale'},
  {id: '529', displayName: 'Louisville'},
  {id: '530', displayName: 'Tallahassee/Thomasville'},
  {id: '531', displayName: 'Tri-Cities-Tn-Va'},
  {id: '532', displayName: 'Albany/Schenectady/Troy'},
  {id: '533', displayName: 'Harford/New Haven'},
  {id: '534', displayName: 'Orlando/Daytona Beach/Melbourne'},
  {id: '535', displayName: 'Columbus-Oh'},
  {id: '536', displayName: 'Youngstown'},
  {id: '537', displayName: 'Bangor'},
  {id: '538', displayName: 'Rochester-Ny'},
  {id: '539', displayName: 'Tampa/Saint Petersburg'},
  {id: '540', displayName: 'Traverse City/Cadillac'},
  {id: '541', displayName: 'Lexington'},
  {id: '542', displayName: 'Dayton'},
  {id: '543', displayName: 'Springfield/Holyoke'},
  {id: '544', displayName: 'Norfolk/Portsmouth/Newport News'},
  {id: '545', displayName: 'Greenville/New Bern/Washington'},
  {id: '546', displayName: 'Columbia-Sc'},
  {id: '547', displayName: 'Toledo'},
  {id: '548', displayName: 'West Palm Beach/Fort Pierce'},
  {id: '549', displayName: 'Watertown'},
  {id: '550', displayName: 'Wilmington'},
  {id: '551', displayName: 'Lansing'},
  {id: '552', displayName: 'Presque Isle'},
  {id: '553', displayName: 'Marquette'},
  {id: '554', displayName: 'Wheeling/Steubenville'},
  {id: '555', displayName: 'Syracuse'},
  {id: '556', displayName: 'Richmond/Petersburg'},
  {id: '557', displayName: 'Knoxville'},
  {id: '558', displayName: 'Lima'},
  {id: '559', displayName: 'Bluefield/Beckley/Oak Hill'},
  {id: '560', displayName: 'Raleigh/Durham'},
  {id: '561', displayName: 'Jacksonville-Brunswick'},
  {id: '563', displayName: 'Grand Rapids/Kalamazoo/Battle Creek'},
  {id: '564', displayName: 'Charleston/Huntington'},
  {id: '565', displayName: 'Elmira'},
  {id: '566', displayName: 'Harrisburg/Lancaster/Lebanon/York'},
  {id: '567', displayName: 'Greenville/Spartanburg/Asheville/Anderson'},
  {id: '569', displayName: 'HarrisonBurg'},
  {id: '570', displayName: 'Florence/Myrtle Beach'},
  {id: '571', displayName: 'Fort Myers/Naples'},
  {id: '573', displayName: 'Roanoke/Lynchburg'},
  {id: '574', displayName: 'Johnstown/Altoona'},
  {id: '575', displayName: 'Chattanooga'},
  {id: '576', displayName: 'Salisbury'},
  {id: '577', displayName: 'Wilkes Barre/Scranton'},
  {id: '581', displayName: 'Terre Haute'},
  {id: '582', displayName: 'Lafayette-In'},
  {id: '583', displayName: 'Alpena'},
  {id: '584', displayName: 'Charlottesville'},
  {id: '588', displayName: 'South Bend/Elkhart'},
  {id: '592', displayName: 'Gainesville'},
  {id: '596', displayName: 'Zanesville'},
  {id: '597', displayName: 'Parkersburg'},
  {id: '598', displayName: 'Clarksburg/Weston'},
  {id: '600', displayName: 'Corpus Christi'},
  {id: '602', displayName: 'Chicago'},
  {id: '603', displayName: 'Joplin/Pittsburg'},
  {id: '604', displayName: 'Columbia/Jefferson City'},
  {id: '605', displayName: 'Topeka'},
  {id: '606', displayName: 'Dothan'},
  {id: '609', displayName: 'Saint Louis'},
  {id: '610', displayName: 'Rockford'},
  {id: '611', displayName: 'Rochester/Mason City/Austin'},
  {id: '612', displayName: 'Shreveport'},
  {id: '613', displayName: 'Minneapolis/Saint Paul'},
  {id: '616', displayName: 'Kansas City'},
  {id: '617', displayName: 'Milwaukee'},
  {id: '618', displayName: 'Houston'},
  {id: '619', displayName: 'Springfield-Mo'},
  {id: '622', displayName: 'New Orleans'},
  {id: '623', displayName: 'Dallas/Fort Worth'},
  {id: '624', displayName: 'Sioux City'},
  {id: '625', displayName: 'Waco/Temple/Bryan'},
  {id: '626', displayName: 'Victoria'},
  {id: '627', displayName: 'Wichita Falls/Lawton'},
  {id: '628', displayName: 'Monroe/El Dorado'},
  {id: '630', displayName: 'Birmingham'},
  {id: '631', displayName: 'Ottumwa/Kirksville'},
  {id: '632', displayName: 'Paducah/Cape Giradeau/Harrisburg/Mt Vernon'},
  {id: '633', displayName: 'Odessa/Midland'},
  {id: '634', displayName: 'Amarillo'},
  {id: '635', displayName: 'Austin-Tx'},
  {id: '636', displayName: 'Harlingen/Weslaco/Brownsville/Mcallen'},
  {id: '637', displayName: 'Cedar Rapids/Waterloo/Dubuque'},
  {id: '638', displayName: 'Saint Joseph'},
  {id: '639', displayName: 'Jackson-Tn'},
  {id: '640', displayName: 'Memphis'},
  {id: '641', displayName: 'San Antonio'},
  {id: '642', displayName: 'Lafayette-La'},
  {id: '643', displayName: 'Lake Charles'},
  {id: '644', displayName: 'Alexandria-La'},
  {id: '647', displayName: 'Greenwood/Greenville'},
  {id: '648', displayName: 'Champaign/Springfield/Decatur'},
  {id: '649', displayName: 'Evansville'},
  {id: '650', displayName: 'Oklahoma City'},
  {id: '651', displayName: 'Lubbock'},
  {id: '652', displayName: 'Omaha'},
  {id: '656', displayName: 'Panama City'},
  {id: '657', displayName: 'Sherman-Tx/Ada-Ok'},
  {id: '658', displayName: 'Green Bay/Appleton'},
  {id: '659', displayName: 'Nashville'},
  {id: '661', displayName: 'San Angelo'},
  {id: '662', displayName: 'Abilene/Sweetwater'},
  {id: '669', displayName: 'Madison'},
  {id: '670', displayName: 'Fort Smith/Fayetteville/Springdale/Rogers'},
  {id: '671', displayName: 'Tulsa'},
  {id: '673', displayName: 'Columbus/Tupelo/West Point'},
  {id: '675', displayName: 'Peoria/Bloomington'},
  {id: '676', displayName: 'Duluth/Superior'},
  {id: '678', displayName: 'Wichita/Hutchinson'},
  {id: '697', displayName: 'Des Moines/Ames'},
  {id: '682', displayName: 'Davenport/Rock Island/Moline'},
  {id: '686', displayName: 'Mobile/Pensacola/Fort Walton Beach'},
  {id: '687', displayName: 'Minot/Bismark/Dickinson'},
  {id: '691', displayName: 'Huntsville/Decatur/Florence'},
  {id: '692', displayName: 'Beaumont/Port Arthur'},
  {id: '693', displayName: 'Little Rock/Pine Bluff'},
  {id: '698', displayName: 'Montgomery/Selma'},
  {id: '702', displayName: 'La Crosse/Eau Claire'},
  {id: '705', displayName: 'Wausau/Rhinelander'},
  {id: '709', displayName: 'Tyler/Longview/Lufkin/Nacogdoches'},
  {id: '710', displayName: 'Hattiesburg/Laurel'},
  {id: '711', displayName: 'Meridian'},
  {id: '716', displayName: 'Baton Rouge'},
  {id: '717', displayName: 'Quincy/Hannibal/Keokuk'},
  {id: '718', displayName: 'Jackson-Ms'},
  {id: '722', displayName: 'Lincoln/Hastings/Kearney'},
  {id: '724', displayName: 'Fargo/Valley City'},
  {id: '725', displayName: 'Sioux Falls/Mitchell'},
  {id: '734', displayName: 'Jonesboro'},
  {id: '736', displayName: 'Bowling Green'},
  {id: '737', displayName: 'Mankato'},
  {id: '740', displayName: 'North Platte'},
  {id: '743', displayName: 'Anchorage'},
  {id: '744', displayName: 'Honolulu'},
  {id: '745', displayName: 'Fairbanks'},
  {id: '746', displayName: 'Biloxi/Gulfport'},
  {id: '747', displayName: 'Juneau'},
  {id: '749', displayName: 'Laredo'},
  {id: '751', displayName: 'Denver'},
  {id: '752', displayName: 'Colorado Springs/Pueblo'},
  {id: '753', displayName: 'Phoenix'},
  {id: '754', displayName: 'Butte/Bozeman'},
  {id: '755', displayName: 'Great Falls'},
  {id: '756', displayName: 'Billings'},
  {id: '757', displayName: 'Boise'},
  {id: '758', displayName: 'Idaho Falls/Pocatello'},
  {id: '759', displayName: 'Cheyenne/Scottsbluff'},
  {id: '760', displayName: 'Twin Falls'},
  {id: '762', displayName: 'Missoula'},
  {id: '764', displayName: 'Rapid City'},
  {id: '765', displayName: 'El Paso'},
  {id: '766', displayName: 'Helena'},
  {id: '767', displayName: 'Casper/Riverton'},
  {id: '770', displayName: 'Salt Lake City'},
  {id: '771', displayName: 'Yuma, El Centro'},
  {id: '773', displayName: 'Grand Junction/Montrose'},
  {id: '789', displayName: 'Tuscon/Sierra Vista'},
  {id: '790', displayName: 'Albuquerque/Santa Fe'},
  {id: '798', displayName: 'Glendive'},
  {id: '800', displayName: 'Bakersfield'},
  {id: '801', displayName: 'Eugene'},
  {id: '802', displayName: 'Eureka'},
  {id: '803', displayName: 'Los Angeles'},
  {id: '804', displayName: 'Palm Springs'},
  {id: '807', displayName: 'San Francisco/Oakland/San Jose'},
  {id: '810', displayName: 'Yakima/Pasco/Richland/Kennewick'},
  {id: '811', displayName: 'Reno'},
  {id: '813', displayName: 'Medford/Klamath Falls'},
  {id: '819', displayName: 'Seattle/Tacoma'},
  {id: '820', displayName: 'Portland-Or'},
  {id: '821', displayName: 'Bend-Or'},
  {id: '825', displayName: 'San Diego'},
  {id: '828', displayName: 'Monterey/Salinas'},
  {id: '839', displayName: 'Las Vegas'},
  {id: '855', displayName: 'Santa Barbara/Santa Maria/San Luis Obispo'},
  {id: '862', displayName: 'Sacramento/Stockton/Modesto'},
  {id: '866', displayName: 'Fresno'},
  {id: '868', displayName: 'Chico/Redding'},
  {id: '881', displayName: 'Spokane'}
]


export default {
  stateChoices,
  countryChoices,
  dmaChoices
}
